### ISSUE TITLE
Automated creation of `use_foo_query` for server fns

### ISSUE THREAD

**Issue by srid** [nicoburniske/leptos_query#7]
If I have a server function like,

```rust
#[server(GetNixInfo, "/api")]
pub async fn get_nix_info() -> Result<NixInfo, ServerFnError> {
```

would it make sense to extend it as:

```rust
#[server(GetNixInfo, "/api")]
#[query(options=QueryOptions::default)]  // <- Provided by leptos_query
pub async fn get_nix_info() -> Result<NixInfo, ServerFnError> {
```

such that the user does not have to manually write code like this?

```rust
/// Like [QueryResult] but used when calling Leptos [server] functions
type ServerQueryResult<T, R> = QueryResult<Result<T, ServerFnError>, R>;

fn use_nix_info_query(cx: Scope) -> ServerQueryResult<NixInfo, impl RefetchFn> {
    leptos_query::use_query(
        cx,
        || (),
        |()| async move { get_nix_info().await },
        QueryOptions::default(),
    )
}
```

**Comment by srid** [comment]
I imagine that the bulk of this module can be removed, as a result:

https://github.com/juspay/nix-browser/blob/2357d0548a9a51734d654f53104d5306a878abd8/src/query.rs

**Comment by srid** [comment]
I think a better approach is to write generic functions instead of macros. Something like:

```rust
/// Like [use_query] gut for server functions
pub fn use_server_query<S, V>(cx: Scope, k: ReadSignal<S>) -> ServerQueryResult<V, impl RefetchFn>
where
    S: Hash + Eq + Clone + 'static,
    ServerQueryVal<V>: Clone + Serializable + 'static,
    S: Clone + ServerFn,
{
    let action = create_server_action::<S>(cx);
    leptos_query::use_query(
        cx,
        k,
        |k| async move {
            action.dispatch(k);
            action.value()
        },
        query_options::<ServerQueryVal<V>>(),
    )
}

type ServerQueryResult<T, R> = QueryResult<ServerQueryVal<T>, R>;
type ServerQueryVal<T> = Result<T, ServerFnError>;
```

(This code ^ does't compile, I'm still working on it)

**Comment by nicoburniske** [comment]
I think the macro will be very difficult because server functions can have variable arguments. 

As far as you second point, I think there is some sort of conflation between Server Actions, and Server Functions. 

[Server actions are for mutative operations](https://leptos-rs.github.io/leptos/async/13_actions.html). These operations are still async, but most of the behavior does not fall under the domain of `use_query`. Queries are more like enhanced leptos resources. 

Tanstack Query does include a `useMutation` function that tries to cover this, including callbacks for `onSuccess`, `onFailure`, and other niceties. Do you think this is something worth adding to leptos_query? Perhaps as an optional feature? I am not opposed to it. 

https://tanstack.com/query/v4/docs/react/guides/mutations

**Comment by srid** [comment]
@nicoburniske I wasn't talking about mutative operations (which doesn't belong to leptos_query). Actually I have a more precise request; will open a new issue to talk about it.

**Comment by srid** [comment]
contd. #8
